name: Sync Image to Aliyun
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space (Aggressive Clean)
        run: |
          echo "Before cleaning:"
          df -h
          # 删掉所有没用的大家伙
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          # 清理 apt 缓存
          sudo apt-get clean
          echo "After cleaning:"
          df -h

      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Sync Image using Skopeo
        run: |
          SOURCE_IMAGE="docker://docker.io/efabless/iic-osic-tools:latest"
          # 注意：请再次核对下面这个 crpi-xxxx 地址是你阿里云仓库的【公网地址】
          TARGET_IMAGE="docker://${{ secrets.ALIYUN_REGISTRY }}/lna-1/lna-design1:latest"
          
          echo "Starting sync..."
          skopeo copy --src-no-creds --dest-creds "${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}" \
          $SOURCE_IMAGE $TARGET_IMAGE
