name: Sync Image to Aliyun
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space (Aggressive Clean)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt-get clean

      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Sync Image using Skopeo
        run: |
          # 关键修改：改用 GitHub 官方仓库 ghcr.io 作为源
          # 内部拉取 GitHub 自己的镜像，不需要登录，也不会被拒绝
          SOURCE_IMAGE="docker://ghcr.io/efabless/iic-osic-tools:latest"
          
          # 你的阿里云目标地址
          TARGET_IMAGE="docker://${{ secrets.ALIYUN_REGISTRY }}/lna-1/lna-design1:latest"
          
          echo "Starting sync from GHCR to Aliyun..."
          
          # 执行同步
          skopeo copy --src-no-creds --dest-creds "${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}" \
          $SOURCE_IMAGE $TARGET_IMAGE
